### ISSUE TITLE
config 无法添加 ignores 属性

### ISSUE THREAD

**Issue by sunpm** [KeJunMao/eslint-config#12]
### Describe the bug

<img width="630" alt="image" src="https://github.com/uni-helper/eslint-config/assets/35005831/5d34c041-c735-48f1-b2ea-7c569bc8e29f">
<img width="695" alt="image" src="https://github.com/uni-helper/eslint-config/assets/35005831/597db45a-c02a-4824-b138-8b578cc96a48">

### Reproduction

```eslint.config.js
const uni = require('@uni-helper/eslint-config')
const unocss = require('@unocss/eslint-plugin')

module.exports = uni(
  {
    overrides: {
      uni: {
        'vue/component-name-in-template-casing': ['error', 'PascalCase'],
      },
    },
    ignores: [
      './src/**/*.js',
    ],
  },
  unocss.configs.flat,
)

```
 "eslint": "^8.56.0",
 "@uni-helper/eslint-config": "^0.0.6",
  "@unocss/eslint-config": "^0.58.3",

### System Info

```Shell
System:
    OS: macOS 12.6.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 356.16 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/Library/Caches/fnm_multishells/4880_1706113613238/bin/node
    Yarn: 1.22.21 - ~/Library/Caches/fnm_multishells/4880_1706113613238/bin/yarn
    npm: 10.2.3 - ~/Library/Caches/fnm_multishells/4880_1706113613238/bin/npm
  Browsers:
    Chrome: 123.0.6312.107
    Safari: 16.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dockfries** [comment]
去掉相对路径./试试，虽然我不知道为什么，但是我去掉是有用的

**Comment by sunpm** [comment]
> 去掉相对路径./试试，虽然我不知道为什么，但是我去掉是有用的

你是对的，thanks
