### ISSUE TITLE
升级模块依赖版本

### ISSUE THREAD

**Issue by peerless-hero** [KeJunMao/eslint-config#13]
### 对问题的清晰和简明的描述

截至目前， @antfu/eslint-config 的版本更新到了2.21.2 ，对应的eslint版本也升级到了9.5.0（虽然是补丁版：npm:eslint-ts-patch@9.5.0-0）。
而本仓库已经6个月未更新了......

### 推荐的解决方案

更新并适配@antfu/eslint-config 和eslint的新版本。

### 额外上下文

[https://github.com/antfu/eslint-config](https://github.com/antfu/eslint-config)

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by ModyQyW** [comment]
v0.1.0
