### ISSUE TITLE
组件命名为什么强制调整为 kebab-case 模式呢？

### ISSUE THREAD

**Issue by Ares-Chang** [KeJunMao/eslint-config#5]
### 对问题的清晰和简明的描述

为什么要强制锁定组件命名模式呢？我并不是很能接受自定义组件 kebab-case 写法。

https://github.com/uni-helper/eslint-config/blob/2bbdf420beb42296a9628738159d8747b7ce6760/src/configs/uni.ts#L14-L16

这个地方如果不设置的话，antfu 默认应该是 `registeredComponentsOnly: true` [仅检查已注册的组件](https://eslint.vuejs.org/rules/component-name-in-template-casing.html) ，应该是不会影响到 `uni-app` 原生标签的。

### 推荐的解决方案

虽然可以自定义修改规则，但我觉得保持默认是最好的选择。

> ps: 是不是最好能提供一下怎么自定义规则文档，我刚刚在第一个参数里直接写了规则，ts 也没有报错，我就以为配置成功了，但是半天不生效，所以我去看了源码好像不是这样用的 :)。

### 替代方案

![image](https://github.com/uni-helper/eslint-config/assets/36911513/0fc70bde-c89f-4cdb-9318-397af73e7556)

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by KeJunMao** [comment]
因为 uniapp 不认 `Navigator` 只认 `navigator`

**Comment by KeJunMao** [comment]
当然这只是随便举了一个例子，大部分组件都不认 PascalCase 的写法。

之前本来是这样写的，即排除 uni 内置组件，其余使用 PascalCase 

https://github.com/uni-helper/eslint-config/commit/1b77cac9255fb715bcd2d7e827202fd3d098deb3#diff-e0b6eda861d6d92a8131d57ed5c90f8359f71ac844d5dc7889188cd7b1abe16eL14-L72

但是这样的问题就是命名风格不统一。

**Comment by Ares-Chang** [comment]
所以是否有必要强制锁定，按照默认配置，`registeredComponentsOnly` 不设置为 `false` 的话，不会产生强制转换，只会更改注册组件名称

**Comment by KeJunMao** [comment]
> 所以是否有必要强制锁定，按照默认配置，`registeredComponentsOnly` 不设置为 `false` 的话，不会产生强制转换，只会更改注册组件名称

这个确实没有必要，我的问题。

**Comment by KeJunMao** [comment]
对于 uni-app 来说，`view`、`navigator` 就像是 `div`、`a` ，所以我们应该将其添加到 `ignores` 列表中。
同时 `registeredComponentsOnly` 改为 `true` 然后还是坚持使用 `PascalCase` 如何？

**Comment by Ares-Chang** [comment]
💕感谢，突然迁移至 kebab-case 不是特别适应。

但是这样是否有必要，`registeredComponentsOnly` 设置为 `true` 后不会对 UniApp 原生内容产生任何影响，因为它不会注册为组件。

[link](https://eslint.vuejs.org/rules/component-name-in-template-casing.html)

它的默认配置就是 

```ts
{
  "vue/component-name-in-template-casing": ["error", "PascalCase" | "kebab-case", {
    "registeredComponentsOnly": true,
    "ignores": []
  }]
}
```

![image](https://github.com/uni-helper/eslint-config/assets/36911513/4351b40e-0947-47f3-9986-7ca31d777119)

我刚刚测试，貌似只有主动页面 `import` 后使用组件，规则才会被触发
