### ISSUE TITLE
webstorm 上面报错，不知道是不是我的个例

### ISSUE THREAD

**Issue by sunpm** [KeJunMao/eslint-config#9]
### 描述问题

```bash
Error: Invalid Options:
- Unknown options: reportUnusedDisableDirectives
- 'reportUnusedDisableDirectives' has been removed. Please use the 'overrideConfig.linterOptions.reportUnusedDisableDirectives' option instead.
```

<img width="1341" alt="image" src="https://github.com/uni-helper/eslint-config/assets/35005831/9ee1a0f8-5697-4206-ac1a-0996a567d01e">

### 复现

<img width="767" alt="image" src="https://github.com/uni-helper/eslint-config/assets/35005831/500ea351-0126-434c-bf51-5f35e35ebcc5">
<img width="1656" alt="image" src="https://github.com/uni-helper/eslint-config/assets/35005831/ff8160ff-6088-4220-9950-ba2b98a01a49">

### 系统信息

```Shell
System:
    OS: macOS 12.6.5
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 172.86 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 120.0.6099.109
    Firefox: 63.0.3
```

### 使用的包管理器

yarn

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KongBaiVso** [comment]
1. 如果 eslint > 8.55.0，可以试试降级到8.50.0
2. 试着按提示上面修改依赖库里的 eslint 规则

**Comment by sunpm** [comment]
> 1. 如果 eslint > 8.55.0，可以试试降级到8.50.0
> 2. 试着按提示上面修改依赖库里的 eslint 规则

好的，感谢
